find_path(SimpleDBSCAN_INCLUDE_DIR NAMES dbscan.h PATHS ${CONAN_INCLUDE_DIRS_SimpleDBSCAN})
find_library(SimpleDBSCAN_LIBRARY NAMES ${CONAN_LIBS_SimpleDBSCAN} PATHS ${CONAN_LIB_DIRS_SimpleDBSCAN})

set(SimpleDBSCAN_FOUND TRUE)
set(SimpleDBSCAN_INCLUDE_DIRS ${Simple_DBSCAN_INCLUDE_DIR})
set(SimpleDBSCAN_LIBRARIES ${Simple_DBSCAN_LIBRARY})
mark_as_advanced(reshaper_LIBRARY reshaper_INCLUDE_DIR)
